version: '3'
services:
  kubernetes:
    build:
      context: .
      dockerfile: ./k8s_mock/Dockerfile
    # image: ravisharma11/kind:v1
    command: "demo-cluster"
    ports:
      - "8001:8001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./k8s_mock/configs/:/configs"

  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  aws-s3-seed:
    image: mesosphere/aws-cli
    depends_on:
      - localstack
    entrypoint: /aws/setup-aws.py
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_SESSION_TOKEN=baz
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - ./aws_mock:/aws

  mock-server:
    image: pretenders/pretenders:1.4
    ports:
      - "7686:9000"
